version: '2'
services:
    cleaneat-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/cleaneat/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=cleaneat
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
